name: Build NixOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-nixos:
    runs-on: ubuntu-latest

    steps:
      - name: Show CPU info
        run: |
          echo "uname -a:"
          uname -a
          echo
          echo "lscpu:"
          lscpu || true
          echo
          echo "/proc/cpuinfo (first block):"
          sed -n '1,25p' /proc/cpuinfo

      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            experimental-features = nix-command flakes
            system-features = nixos-test benchmark big-parallel kvm gccarch-x86-64-v4
            max-jobs = auto
            keep-going = true

      - name: Build minimal NixOS system
        run: |
          nix build .#nixosConfigurations.nixos.config.system.build.toplevel
          readlink -f result

      - name: Upload system closure as artifact
        uses: actions/upload-artifact@v4
        with:
          name: nixos-minimal-system
          path: result
